version: "3"

services:

  spark-iceberg:
      build:
        context: ./config/aio
        dockerfile: dockerfile
      container_name: spark-iceberg
      networks:
        dwh_network:
      volumes:
        - ./projects/spark/notebooks:/home/iceberg/notebooks
        - ./config/aio/spark/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
        - ./config/aio/dagster/dagster.yaml:/opt/dagster/dagster.yaml
        - ./projects/dagster:/var/lib/adventureworks/dagster
        - ./projects/dbt:/var/lib/adventureworks/dbt
        - ./config/aio/entrypoint.sh:/opt/spark/entrypoint.sh
      environment:
        - AWS_ACCESS_KEY_ID=minio
        - AWS_SECRET_ACCESS_KEY=minio123
        - AWS_REGION=us-east-1
        - AWS_ENDPOINT=http://minio:9000
        - AW_CORE_HOST=adventure-works-core-mysql
        - AW_CORE_PORT=3306
        - AW_CORE_DATABASE=adventureworks
        - AW_CORE_USER=user
        - AW_CORE_PASSWORD=password
        - AW_HR_FILES_HOST=adventure-works-employees-files
        - AW_HR_FILES_PORT=8080
        - AW_REVIEWS_API_HOST=adventure-works-reviews-api
        - AW_REVIEWS_API_PORT=8000
      ports:
        - ${JUPYTER_SERVER_PORT}:8888
        - ${DAGSTER_ADMIN_PORT}:3070
       



networks:
  dwh_network:
    external:
      name: ${DOCKER_NETWORK}