trino:
  target: dev
  outputs:
    dev:
      type: trino
      user: trino
      host: trino
      port: 8060
      database: warehouse
      schema: silver
      threads: 1
      http_scheme: http
      session_properties:
        query_max_run_time: 5d